

# This file was *autogenerated* from the file error_estimate.sage
from sage.all_cmdline import *   # import sage library

_sage_const_512 = Integer(512); _sage_const_2 = Integer(2); _sage_const_27 = Integer(27); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1024 = Integer(1024); _sage_const_7 = Integer(7); _sage_const_1p0 = RealNumber('1.0'); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_23 = Integer(23); _sage_const_25 = Integer(25); _sage_const_12 = Integer(12); _sage_const_23p7691 = RealNumber('23.7691')# FHEW system parameters
## LWE parameters
n = _sage_const_512 
Q = _sage_const_2 **_sage_const_27 
sigma = _sage_const_1p4 
q = _sage_const_512 
## Ring-GSW parameters
N = _sage_const_1024 
stigma = sigma
## Gadget Matrix
Bg = _sage_const_2 **_sage_const_7 
dg = ceil(_sage_const_1p0 *log(Q, Bg))
u = Q/_sage_const_8  + _sage_const_1 
## Bootstrapping Key Parameters
Br = _sage_const_23 
dr = ceil(_sage_const_1p0 *log(q, Br))
# Key Switching Key Parameters
Bks = _sage_const_25 
dks = ceil(_sage_const_1p0 *log(Q, Bks))

# standard deviation of the final error err(Refresh(c)), modelled as Gaussian distribution, the coeff 240 is debatable.
beta = sqrt((q**_sage_const_2 )/(Q**_sage_const_2 ) * (stigma**_sage_const_2  * (_sage_const_1 *Bg**_sage_const_2 )/_sage_const_12  *n*dr * (q/_sage_const_2 ) * _sage_const_2 *N*dg + sigma**_sage_const_2 *N*dks) + (n/_sage_const_2  + _sage_const_1 )/_sage_const_12 ) 
beta = sqrt(_sage_const_23p7691 )
# error probability per NAND
r = (q/_sage_const_8 )/(sqrt(_sage_const_2 )*beta)
p = int(log(_sage_const_1  - erf(r/sqrt(_sage_const_2 )), _sage_const_2 ))
# p = 1 - erf(r/sqrt(2))

print ("Standard deviation of NAND gate: " + str(beta))
print ("DFR per NAND gate: 2^({p})".format(p = p))

